Repository LLocke8/LudumDare55, pull requests merged in 2024-04, with the labels that each got.

#2 File iniziali e configurazione
  .gitattributes
  .gitignore
  export_presets.cfg
  icon.svg
  icon.svg.import
  project.godot
Labels: Coding

#3 Aggiornamento Main
  .gitattributes
  .gitignore
  export_presets.cfg
  icon.svg
  icon.svg.import
  project.godot
Labels: Coding

#4 Fix gitignore
  .gitignore
Labels: Coding

#28 Flusso di gioco
  Sistemi/GameManager.gd
  Sistemi/Game_Manager.tscn
  carta.tscn
Labels: Design, Coding

#35 Unità strutture
  Entity/Entity.gd
  Entity/Entity.tscn
  Entity/Structure/Structure.gd
  Entity/Structure/Structure.tscn
  Entity/Traits/Aggro.gd
  Entity/Traits/Aggro.tscn
  Entity/Unit/Uni89E.tmp
  Entity/Unit/Unit.gd
  Entity/Unit/Unit.tscn
  Test.tscn
  project.godot
Labels: Coding

#42 Unita strutture base
  Entity/Entity.gd
  Entity/Entity.tscn
  Entity/Structure/Coffin/Coffin.gd
  Entity/Structure/Coffin/Coffin.png
  Entity/Structure/Coffin/Coffin.png.import
  Entity/Structure/Coffin/Coffin.tscn
  Entity/Structure/Structure.gd
  Entity/Structure/Wall/Muro di tronchi.png
  Entity/Structure/Wall/Muro di tronchi.png.import
  Entity/Structure/Wall/Wall.gd
  Entity/Structure/Wall/Wall.tscn
  Entity/Structure/Wisp turret/Torretta Scheletro.png
  Entity/Structure/Wisp turret/Torretta Scheletro.png.import
  Entity/Structure/Wisp turret/Wisp turret.gd
  Entity/Structure/Wisp turret/Wisp turret.tscn
  Entity/Traits/Aggro.gd
  Entity/Traits/Aggro.tscn
  Entity/Traits/Attack.gd
  Entity/Traits/Attack.tscn
  Entity/Unit/Shield Skeleton/Scheletro Scudo.png
  Entity/Unit/Shield Skeleton/Scheletro Scudo.png.import
  Entity/Unit/Shield Skeleton/Shield Skeleton.gd
  Entity/Unit/Shield Skeleton/Shield Skeleton.tscn
  Entity/Unit/Skeleton Archer/Scheletro Arco.png
  Entity/Unit/Skeleton Archer/Scheletro Arco.png.import
  Entity/Unit/Skeleton Archer/Skeleton Archer.gd
  Entity/Unit/Skeleton Archer/Skeleton Archer.tscn
  Entity/Unit/Sword Skeleton/Scheletro Spada.png
  Entity/Unit/Sword Skeleton/Scheletro Spada.png.import
  Entity/Unit/Sword Skeleton/Sword_Skeleton.gd
  Entity/Unit/Sword Skeleton/Sword_Skeleton.tscn
  Entity/Unit/Unit.gd
  Entity/Unit/Unit.tscn
  Tes3907.tmp
  Tes402.tmp
  Tes5145.tmp
  Tes5283.tmp
  Test.tscn
  carta.tscn
  project.godot
Labels: Design, Graphics, Coding

#43 UI 2
  Sistemi/Hp.png
  Sistemi/Hp.png.import
  Sistemi/Hud.png
  Sistemi/Hud.png.import
  Sistemi/Soul.png
  Sistemi/Soul.png.import
  Sistemi/StartButton.png
  Sistemi/StartButton.png.import
  Sistemi/UI.tscn
Labels: Design, Graphics, Coding

#49 Mappa principale
  Map/Main_map.tscn
  Map/SpawnLocation.tscn
  Map/Spawner.gd
  Scenes/SpawnLocation.tscn
  Scenes/Wor9A3.tmp
  Sistemi/Game_Manager.tscn
  Sistemi/UI.tscn
Labels: Coding

#52 Mazzo2.0
  Carte/CardData.gd
  Carte/Deck_Manager.gd
  Carte/car4EC1.tmp
  Carte/carEB9C.tmp
  Carte/carta.gd
  Carte/carta.tscn
  Carte/pla2BE6.tmp
  Carte/pla34E5.tmp
  font/Comfortaa-Bold.ttf
  font/Comfortaa-Bold.ttf.import
  project.godot
Labels: Coding

#68 Hp Bar full
  Entity/Entity.gd
  Entity/Entity.tscn
  Entity/Hp/hp_bar.gd
  Entity/Hp/hp_bar.tscn
  Entity/Structure/Coffin/Coffin.tscn
  Entity/Structure/Wall/Wall.tscn
  Entity/Traits/Attack.gd
  Entity/Unit/Sword Skeleton/Sword_Skeleton.gd
  TesD133.tmp
  Test.tscn
Labels: Design, Graphics, Coding

#70 Fixato cosa???
  Entity/Entity.gd
Labels: Coding

#71 Hpbarfix
  Entity/Entity.gd
  Entity/Entity.tscn
  Entity/Hp/hp_bar.gd
  Entity/Hp/hp_bar.tscn
Labels: Design, Graphics, Coding

#78 Archer bugfix
  Carte/Deck_Manager.gd
  Entity/Structure/Coffin/Coffin.gd
  Entity/Structure/Wisp turret/Wisp turret.gd
  Entity/Structure/Wisp turret/Wisp turret.tscn
  Entity/Traits/Attack.gd
  Entity/Unit/Mage Skeleton/Mage Skeleton.gd
  Entity/Unit/Mage Skeleton/Mage Skeleton.tscn
  Entity/Unit/Skeleton Archer/Skeleton Archer.gd
  Entity/Unit/Skeleton Archer/Skeleton Archer.tscn
  Entity/Unit/Unit.gd
  Map/Spawner.gd
  Sistemi/GameManager.gd
  Sistemi/UI.tscn
Labels: maintenance

#27 Menu 1.0
  Game_Over/Game_over.gd
  Game_Over/Game_over.tscn
  Main_menu/Options_menu/aud9718.tmp
  Main_menu/Options_menu/audio_slider_settings.gd
  Main_menu/Options_menu/audio_slider_settings.tscn
  Main_menu/Options_menu/display.tscn
  Main_menu/Options_menu/options.gd
  Main_menu/Options_menu/options.tscn
  Main_menu/Options_menu/set85D8.tmp
  Main_menu/Options_menu/set9E51.tmp
  Main_menu/Options_menu/setCA89.tmp
  Main_menu/Options_menu/settings_tab_container.tscn
  Main_menu/Options_menu/windows_mode_button.gd
  Main_menu/Options_menu/windows_mode_button.tscn
  Main_menu/main_menu.gd
  Main_menu/main_menu.tscn
  Main_menu/main_menu_styles.tres
  Victory/victory.gd
  Victory/victory.tscn
  background/GameOver.jpg
  background/GameOver.jpg.import
  background/GameOver1.jpg.import
  background/background.jpg
  background/background.jpg.import
  background/menubackgroundsfocato.jpg.import
  background/prova.png
  background/prova.png.import
  background/victory.jpg
  background/victory.jpg.import
  bus_layout/default_bus_layout.tres
  fonts/DUNGRG__.TTF
  fonts/DUNGRG__.TTF.import
  fonts/Dungeon Depths.ttf
  fonts/Dungeon Depths.ttf.import
  fonts/MedievalSharp-Regular.ttf
  fonts/MedievalSharp-Regular.ttf.import
  fonts/The Lost Dungeon.ttf
  fonts/The Lost Dungeon.ttf.import
  music/prova.mp3
  music/prova.mp3.import
  project.godot
Labels: Design, Graphics, Coding

#80 UI aggiornata
  Carte/CardData.gd
  PescataDeck.gd
  Sistemi/BACKDECK.png
  Sistemi/BACKDECK.png.import
  Sistemi/BackCarta.png
  Sistemi/BackCarta.png.import
  Sistemi/Cuore_HP_nemici.png
  Sistemi/Cuore_HP_nemici.png.import
  Sistemi/GameManager.gd
  Sistemi/Hp.png
  Sistemi/Soul.png
  Sistemi/UI.gd
Labels: Design, Graphics, Coding

#83 Livelli
  Carte/CardData.gd
  Carte/Deck_Manager.gd
  Entity/Structure/Coffin/Coffin.tscn
  Entity/Structure/Wisp turret/Wisp turret.gd
  Entity/Structure/Wisp turret/Wisp turret.tscn
  Entity/Unit/Living Wisp/Living_Wisp.tscn
  Entity/Unit/Mage Skeleton/Mage Skeleton.gd
  Entity/Unit/Mage Skeleton/Mage Skeleton.tscn
  Entity/Unit/Phantom/Phantom.tscn
  Entity/Unit/Shield Skeleton/Shield Skeleton.tscn
  Entity/Unit/Skeleton Archer/Skeleton Archer.tscn
  Entity/Unit/Sword Skeleton/Sword_Skeleton.gd
  Entity/Unit/Sword Skeleton/Sword_Skeleton.tscn
  Map/Decorazioni/Acqualati.png
  Map/Decorazioni/Acqualati.png.import
  Map/Decorazioni/AquaLatidritti.png
  Map/Decorazioni/AquaLatidritti.png.import
  Map/Decorazioni/Pavimenti2i.png
  Map/Decorazioni/Pavimenti2i.png.import
  Map/Decorazioni/Shieldl.png
  Map/Decorazioni/Shieldl.png.import
  Map/Decorazioni/ceppo.png
  Map/Decorazioni/ceppo.png.import
  Map/Decorazioni/decorazioni2.png
  Map/Decorazioni/decorazioni2.png.import
  Map/Decorazioni/decorazioni2.tscn
  Map/Decorazioni/fioreRossoGiallo.png
  Map/Decorazioni/fioreRossoGiallo.png.import
  Map/Decorazioni/flowerRametto.png
  Map/Decorazioni/flowerRametto.png.import
  Map/Decorazioni/pavimenti.png
  Map/Decorazioni/pavimenti.png.import
  Map/Decorazioni/piantina.png
  Map/Decorazioni/piantina.png.import
  Map/Decorazioni/ramoscello.png
  Map/Decorazioni/ramoscello.png.import
  Map/Decorazioni/tileset2x2.png
  Map/Decorazioni/tileset2x2.png.import
  Map/Livelli/Liv3184.tmp
  Map/Livelli/LivFFE6.tmp
  Map/Livelli/Livello1.tscn
  Map/Livelli/Livello2.tscn
  Map/Livelli/Livello3.tscn
  Map/Livelli/Livello4.tscn
  Map/Main_map.tscn
  Map/Spawner.gd
  Sistemi/GameManager.gd
Labels: Coding

#84 Integrazione menu save
  Game_Over/Game_over.gd
  Map/Main_map.tscn
  Scenes/Game_Over/Game_over.gd
  Scenes/Game_Over/Game_over.tscn
  Scenes/Main_menu/Options_menu/aud9718.tmp
  Scenes/Main_menu/Options_menu/audio_slider_settings.gd
  Scenes/Main_menu/Options_menu/audio_slider_settings.tscn
  Scenes/Main_menu/Options_menu/display.tscn
  Scenes/Main_menu/Options_menu/options.gd
  Scenes/Main_menu/Options_menu/options.tscn
  Scenes/Main_menu/Options_menu/set85D8.tmp
  Scenes/Main_menu/Options_menu/set9E51.tmp
  Scenes/Main_menu/Options_menu/setCA89.tmp
  Scenes/Main_menu/Options_menu/settings_tab_container.tscn
  Scenes/Main_menu/Options_menu/windows_mode_button.gd
  Scenes/Main_menu/Options_menu/windows_mode_button.tscn
  Scenes/Main_menu/maiE60A.tmp
  Scenes/Main_menu/main_menu.gd
  Scenes/Main_menu/main_menu.tscn
  Scenes/Main_menu/main_menu_styles.tres
  Scenes/SaveLevel.gd
  Scenes/SaveLevel.tscn
  Scenes/Victory/victory.gd
  Scenes/Victory/victory.tscn
  Scenes/background/GameOver.jpg
  Scenes/background/GameOver.jpg.import
  Scenes/background/GameOver1.jpg.import
  Scenes/background/background.jpg
  Scenes/background/background.jpg.import
  Scenes/background/menubackgroundsfocato.jpg.import
  Scenes/background/prova.png
  Scenes/background/prova.png.import
  Scenes/background/victory.jpg
  Scenes/background/victory.jpg.import
  Sistemi/GameManager.gd
  font/DUNGRG__.TTF
  font/DUNGRG__.TTF.import
  font/Dungeon Depths.ttf
  font/Dungeon Depths.ttf.import
  font/MedievalSharp-Regular.ttf
  font/MedievalSharp-Regular.ttf.import
  font/The Lost Dungeon.ttf
  font/The Lost Dungeon.ttf.import
  project.godot
Labels: Design, Coding

#85 Livelli
  Carte/Deck_Manager.gd
  Entity/Structure/Wisp turret/Wisp turret.tscn
  Map/Livelli/Livello2.tscn
  Map/Livelli/Livello3.tscn
Labels: Design, Coding

#86 Animazioni proiettili
  Entity/Traits/Attack.gd
  Entity/Traits/Attack.tscn
  Entity/Traits/Projectile.tscn
  Entity/Unit/Living Wisp/Living_Wisp.tscn
  Entity/Unit/Phantom/Phantom.tscn
  Entity/Unit/Shield Skeleton/Shield Skeleton.tscn
  Entity/Unit/Sword Skeleton/Sword_Skeleton.tscn
  Entity/Unit/Unit.tscn
Labels: Design, Coding

#88 Final ld bugfixes
  Carte/CardData.gd
  Map/Livelli/Livello2.tscn
  Map/Livelli/Livello3.tscn
  Sistemi/GameManager.gd
  export_presets.cfg
Labels: maintenance
